### ISSUE TITLE
enable to split an input file

### ISSUE THREAD

**Issue by ToruNiina** [ToruNiina/Mjolnir#11]
Currently, input file contains everything that is needed to run a simulation. It is good to have an option to specify configuration, forcefield, simulator separately.

The input file format will be like this.
```toml
[[systems]]
filename = "system.toml"
[[forcefields]]
filename = "forcefield.toml"
```
